name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          config_timezone: America/Sao_Paulo
          token: ${{ secrets.METRICS_TOKEN }}
          base: header
          plugin_languages: yes
          plugin_habits: yes
          plugin_achievements: yes
          commits_authoring: Henry Cagnini, henryzord, henryzord@users.noreply.github.com, CTISM-Prof-Henry
          config_order: base.header, habits, languages, achievements

