name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: America/Sao_Paulo
          base: ""
          filename: github-metrics.svg
          plugin_languages: yes
          plugin_achievements: yes
          commits_authoring: Henry Cagnini, henryzord, henryzord@users.noreply.github.com, CTISM-Prof-Henry, COPLIN-UFSM
          config_order: languages, achievements
